apiVersion: apps/v1
kind: Deployment

metadata:
  name: react-vite-app
  namespace: react-app

  labels:
    app: react-vite

spec:
  replicas: 2

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: react-vite

  template:
    metadata:
      labels:
        app: react-vite

    spec:
      containers:

      - name: react-vite-container

        image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPOSITORY_NAME>:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
