apiVersion: v1
kind: Namespace
metadata:
  name: react-app
  labels:
    name: react-app
    app.kubernetes.io/name: react-vite
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: kubectl
