apiVersion: v1
kind: Service

metadata:
  name: react-vite-service
  namespace: react-app

spec:
  type: LoadBalancer

  selector:
    app: react-vite

  ports:

  - port: 80
    targetPort: 80
    protocol: TCP
